# Generated by Django 4.2 on 2025-04-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_unsubscribed'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailopentracking',
            unique_together={('lead', 'email_log')},
        ),
    ]
