# Generated by Django 4.2 on 2025-03-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='emails.emaillog')),
            ],
        ),
    ]
