# Generated by Django 4.2 on 2025-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_clicklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('bounced', 'Bounced')], default='sent', max_length=50),
        ),
    ]
