# Generated by Django 4.2 on 2025-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connected_accounts', '0002_connectedaccount_imap_port_connectedaccount_password_and_more'),
        ('emails', '0003_alter_emaillog_body_alter_emaillog_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connected_accounts.connectedaccount')),
            ],
        ),
    ]
