# Generated by Django 4.2 on 2025-03-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_score_remove_lead_source'),
        ('emails', '0003_alter_emaillog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClickTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='emails.emaillog')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='leads.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='ClickLog',
        ),
    ]
