# Generated by Django 4.2 on 2025-03-11 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailclicktracking_delete_clicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='sender',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
