# Generated by Django 4.2 on 2025-03-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_score_remove_lead_source'),
        ('emails', '0005_emaillog_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReplyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='emails.emaillog')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOpenTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_opens', to='emails.emaillog')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_opens', to='leads.lead')),
            ],
        ),
    ]
