# Generated by Django 4.2 on 2025-03-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_score_remove_lead_source'),
        ('emails', '0006_emailreplytracking_emailopentracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailreplytracking',
            unique_together={('lead', 'email_log', 'subject')},
        ),
    ]
