# Generated by Django 4.2 on 2025-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_score',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
    ]
