# Generated by Django 4.2 on 2025-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_score_remove_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
