# Generated by Django 4.2 on 2025-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_workflow_status_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
