# Generated by Django 4.2 on 2025-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_unsubscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='workflow_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=50),
        ),
    ]
