# Generated by Django 4.2 on 2025-02-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connected_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
    ]
