# Generated by Django 4.2 on 2025-03-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_alter_campaign_id'),
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0006_lead_unsubscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(choices=[('new', 'New Leads Only'), ('all', 'All Leads')], default='new', max_length=10)),
                ('max_emails_per_day', models.IntegerField(default=50)),
                ('pause_between_emails', models.IntegerField(default=30)),
                ('reply_action', models.CharField(choices=[('stop', 'Stop Workflow'), ('continue', 'Continue Workflow')], default='stop', max_length=10)),
                ('sending_time_start', models.TimeField(default='08:00')),
                ('sending_time_end', models.TimeField(default='18:00')),
                ('sending_days', models.JSONField(default=list)),
                ('unsubscribe_handling', models.CharField(choices=[('remove', 'Remove'), ('exclude', 'Exclude')], default='remove', max_length=10)),
                ('bounce_handling', models.CharField(choices=[('stop', 'Stop Workflow'), ('retry', 'Retry with Another Template'), ('continue', 'Continue Workflow')], default='stop', max_length=10)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecutionStep',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('parent_node_id', models.UUIDField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('node', models.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('credits_consumed', models.IntegerField(blank=True, null=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='LeadStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaillog')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='leads.lead')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowexecutionstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'unique_together': {('lead', 'workflow', 'step')},
            },
        ),
    ]
