# Generated by Django 4.2 on 2025-02-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecutionstep',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionstep',
            name='parent_node_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
