# Generated by Django 4.2 on 2025-04-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_workflow_status'),
        ('workflows', '0002_alter_leadstepstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowexecution')),
            ],
        ),
    ]
