# Generated by Django 4.2 on 2025-03-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emaillog_status'),
        ('workflows', '0003_workflowexecutionstep_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecutionstep',
            name='email_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaillog'),
        ),
    ]
