# Generated by Django 4.2 on 2025-02-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflow_status_alter_workflowexecution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='node',
            field=models.JSONField(),
        ),
    ]
