# Generated by Django 4.2 on 2025-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowexecutionstep_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=50),
        ),
    ]
