# Generated by Django 4.2 on 2025-03-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowexecutionstep_email_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='email_log',
        ),
    ]
