# Generated by Django 4.2 on 2025-02-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflowexecutionstep_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='outputs',
        ),
    ]
