# Generated by Django 4.2 on 2025-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowexecutionstep_email_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecutionstep',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
