# Generated by Django 4.2 on 2025-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_workflowexecutionstep_is_obsolete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='is_obsolete',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
