# Generated by Django 4.2 on 2025-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_remove_workflowexecutionstep_is_obsolete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecutionstep',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
