# Generated by Django 4.2 on 2025-03-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_alter_workflowexecutionstep_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(choices=[('new', 'New Leads Only'), ('all', 'All Leads')], default='new', max_length=10)),
                ('max_emails_per_day', models.IntegerField(default=50)),
                ('pause_between_emails', models.IntegerField(default=30)),
                ('reply_action', models.CharField(choices=[('stop', 'Stop Workflow'), ('continue', 'Continue Workflow')], default='stop', max_length=10)),
                ('sending_time_start', models.TimeField(default='08:00')),
                ('sending_time_end', models.TimeField(default='18:00')),
                ('sending_days', models.JSONField(default=list)),
                ('unsubscribe_handling', models.CharField(choices=[('remove', 'Remove'), ('exclude', 'Exclude')], default='remove', max_length=10)),
                ('bounce_handling', models.CharField(choices=[('stop', 'Stop Workflow'), ('retry', 'Retry with Another Template'), ('continue', 'Continue Workflow')], default='stop', max_length=10)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workflows.workflow')),
            ],
        ),
    ]
