# Generated by Django 4.2 on 2025-03-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_status'),
        ('workflows', '0010_workflowsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='status',
        ),
        migrations.CreateModel(
            name='LeadStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='leads.lead')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowexecutionstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'unique_together': {('lead', 'workflow', 'step')},
            },
        ),
    ]
