# Generated by Django 4.2 on 2025-03-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_remove_emaillog_response_received'),
        ('workflows', '0011_remove_workflowexecution_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionstep',
            name='email_log',
        ),
        migrations.AddField(
            model_name='leadstepstatus',
            name='email_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emaillog'),
        ),
    ]
