# Generated by Django 4.2 on 2025-03-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_remove_workflowexecutionstep_email_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='workflow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='workflows.workflow'),
        ),
    ]
