# Generated by Django 4.2 on 2025-01-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seo_description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(max_length=160),
        ),
    ]
