# Generated by Django 4.2 on 2025-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('campaigns', '0002_alter_emailsequence_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(to='leads.lead'),
        ),
    ]
